version: '3.9'
services:
  app:
    build:
     context: ./
     dockerfile: Dockerfile
    ports:
      - '8001:5000'
    volumes:
      - .:/app
    networks:
      - user-service-network
    depends_on:
      - arcane_user_db

  arcane_user_db:
    image: mariadb
    restart: always
    ports:
      - '3321:3306'
    env_file:
      - ./db/.env
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./db/.dbdata:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/ddl/init-table.sql:/docker-entrypoint-initdb.d/1-init-table.sql
      - ./db/ddl/init-data.sql:/docker-entrypoint-initdb.d/2-init-data.sql
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge