version: '3.9'
services:
  app:
    build:
     context: ./
     dockerfile: Dockerfile
    ports:
      - '8001:5000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    ports:
      - '3321:3306'
    env_file:
      - ./db/.env
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]

    volumes:
      - ./db/.dbdata:/var/lib/mysql